Repository FRONTENDSCHOOL7/jubging, pull requests merged in 2023-11, with the labels that each got.

#125 ✨ #124 회원가입시 프로필 설정 기능 추가
  src/components/common/Profile/ProfileImage.jsx
  src/components/common/Profile/ProfileImageStyle.jsx
  src/pages/Sign/ProfileStart.jsx
Labels: ✨ Feature

#127 ✨ 뉴스레터 관리자 계정 글 불러오기
  src/api/postAPI.jsx
  src/components/Post/NewsPosting.jsx
  src/components/Post/PostFooter/NewsPostFooter.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/Header/UploadHeader.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStyle.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/Post/Post.jsx
  src/pages/Profile/Profile.jsx
Labels: ✨ Feature

#131 ✨ 뉴스레터 불러오기 수정, 무한스크롤 기능 추가
  package-lock.json
  package.json
  src/api/axios.jsx
  src/api/postAPI.jsx
  src/components/Post/NewsPosting.jsx
  src/pages/Home/Home.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Upload/Upload.jsx
  src/recoil/jobgingAtom.js
Labels: ✨ Feature, 🔨 Refactor

#132 💄 네브바, 버튼 UI 수정, useScollTop 훅 추가
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/Navbar/BarButton.jsx
  src/components/common/Navbar/BarButtonStyle.jsx
  src/hook/useScrollTop.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Home/NoFollowHome.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Sign/SignUp.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature, 🎨 Style

#134 ✨ 내 프로필 이미지 업로드 기능 추가
  src/pages/Profile/ProfileModification.jsx
Labels: ✨ Feature

#135 ✨ 홈, 뉴스레터 게시글 좋아요 기능 추가
  src/api/postAPI.jsx
  src/assets/icons/icon-fill-like.svg
  src/components/Post/NewsPosting.jsx
  src/components/Post/PostFooter/NewsPostFooter.jsx
  src/components/Post/PostFooter/PostFooter.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/Post/Posting.jsx
  src/pages/Home/HomePosting.jsx
Labels: ✨ Feature

#137 🔨 검색 기능 및 UI 수정
  src/api/postAPI.jsx
  src/api/profileAPI.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/common/UserList/UserListBox.jsx
  src/components/common/UserList/UserListBoxStyle.jsx
  src/pages/Login/Login.jsx
  src/pages/Search/Contents.jsx
  src/pages/Search/Contents.style.jsx
  src/pages/Search/Search.jsx
Labels: 🔨 Refactor, 🎨 Style

#139 🔨 Modal Refactor
  public/index.html
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/Posting.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/pages/Profile/Profile.jsx
Labels: 🔨 Refactor

#140 ✨ 게시글 작성 시 버튼 활성화
  src/components/common/Header/UploadHeader.jsx
  src/components/common/UserList/UserListBox.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/UploadStyle.jsx
Labels: ✨ Feature

#141 ✨ 회원가입시 프로필 설정
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Sign/ProfileStart.jsx
Labels: ✨ Feature

#142 💄 프로필, 팔로워, 팔로잉 프로필 이미지 적용
  src/pages/Follow/FollowList/FollowerList.jsx
  src/pages/Follow/FollowList/FollowerListStyle.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
  src/pages/Search/Search.jsx
Labels: 🎨 Style

#143 ✨ 로그인 요청 후 토큰 업데이트 함수 호출 로직 추가
  src/api/axios.jsx
  src/pages/Login/Login.jsx
Labels: ✨ Feature

#145 🔨 프로필 편집 Alert창 기능 추가
  src/components/common/Alert/Alert.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileModification.jsx
Labels: 🔨 Refactor

#147 🔨 팔로우 팔로잉 리스트 없을 시 검색 유도 페이지 삽입
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Home/NoFollowHome.jsx
  src/pages/Home/NoFollowHomeStyle.jsx
Labels: 🔨 Refactor

#148 🔨 홈 검색 안내 페이지 수정
  src/pages/Home/Home.jsx
Labels: 🔨 Refactor

#149 🔨 #104 댓글 프로필 이미지 코드 수정
  src/pages/Post/CommentInput.jsx
  src/pages/Post/CommentInputStyle.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostCommentStyle.jsx
Labels: 🔨 Refactor

#150 ✨ #104 댓글 삭제 및 신고 모달창
  src/api/commentAPI.jsx
  src/pages/Post/PostComment.jsx
Labels: ✨ Feature

#151 🔨 프로필 이미지 등록 코드 수정, 유효성 검사 추가
  src/api/signupAPI.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Profile/ProfileImage.jsx
  src/components/common/Profile/ProfileImageStyle.jsx
  src/pages/Profile/ProfileModification.jsx
  src/pages/Profile/ProfileModificationStyle.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Upload/Upload.jsx
Labels: 🔨 Refactor

#152 ✨ #104 댓글 삭제하기 기능 추가
  src/api/commentAPI.jsx
  src/components/common/Modal/Modal.jsx
  src/hook/useModalControl.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
Labels: ✨ Feature

#153 ✨ #104 댓글 신고하기 기능 추가
  src/pages/Post/PostComment.jsx
Labels: ✨ Feature

#154 🐞 게시글 수정 시 원래 글 안나오는 버그 해결
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/Posting.jsx
  src/components/common/Alert/AlertStyled.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/components/common/Profile/ProfileImageStyle.jsx
  src/pages/Post/PostEdit.jsx
Labels: 🐞 BugFix

#155 🎨 #104 댓글 레이아웃 업데이트
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostCommentStyle.jsx
Labels: 🎨 Style

#156 🐞 프로필 피드에서 게시글 수정할 때 기존 글 안넘어가는 버그 해결
  src/components/Post/PostHeader/PostHeader.jsx
  src/pages/Profile/Profile.jsx
Labels: 🐞 BugFix

#157 🔨 댓글 등록 및 UI 수정
  src/api/commentAPI.jsx
  src/components/common/Input/RoundInputStyle.jsx
  src/components/common/Modal/Modal.jsx
  src/pages/Post/CommentInput.jsx
  src/pages/Post/CommentInputStyle.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Profile/Profile.jsx
Labels: 🔨 Refactor

#159 ✨ JSON 데이터를 활용한 채팅 목록 표시 구현
  public/baseprofile.svg
  src/components/common/ChatList/ChatList.jsx
  src/components/common/ChatList/chatdata.json
  src/pages/ChatList/ChatListPage.jsx
Labels: ✨ Feature

#161 🔨 팔로우, 팔로잉 페이지 로딩화면 수정
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
Labels: 🔨 Refactor

#163 💄 검색바, 유저리스트, 프로필 UI 수정, 관리자 atom 수정
  src/components/common/Header/SearchHeader.jsx
  src/components/common/UserList/UserListBoxStyle.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
  src/recoil/jobgingAtom.js
Labels: 🎨 Style

#164 🐞 피드에서 게시글 삭제 안되는 문제 해결
  public/index.html
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/common/Header/UploadHeader.jsx
  src/components/common/Modal/Modal.jsx
Labels: 🐞 BugFix

#165 🎨 코스 등록 UI 수정, 무한스크롤 기능 수정
  src/components/kakaomap/KakaoMap.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/AddCourse/AddCourseStyle.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/AddCourse/PathDrawStyle.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
  src/pages/Home/Home.jsx
  src/pages/NewsLetter/NewsLetter.jsx
Labels: 🐞 BugFix, 🎨 Style

#166 🔨 카카오맵 경로 등록 경고창 추가
  src/components/common/Alert/Alert.jsx
  src/components/kakaomap/KakaoMap.jsx
Labels: 🔨 Refactor

#167 💄 스플래쉬, loginStart UI 수정
  src/assets/images/bear-face.png
  src/assets/images/bear-face.svg
  src/assets/images/dog-face.png
  src/assets/images/dog-face.svg
  src/assets/images/logo-white.png
  src/assets/images/rabbit-face.png
  src/assets/images/rabbit-face.svg
  src/components/Splash/Frame/Title.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/Login/LoginStartStyle.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: 🎨 Style

#168 ✨ 공유 버튼 url 복사 기능 추가, 댓글 프로필이미지 Link 추가
  src/components/common/Header/HeaderContainerStyle.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostCommentStyle.jsx
  src/pages/Profile/ProfileDetail.jsx
Labels: ✨ Feature, 🔨 Refactor

#170 🔥 필요없는 코드 및 콘솔, 주석 제거
  src/api/axios.jsx
  src/api/loginAPI.jsx
  src/api/postAPI.jsx
  src/api/signupAPI.jsx
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/PostMain/PostMain.jsx
  src/components/Post/Posting.jsx
  src/components/Splash/Character/Bear.jsx
  src/components/Splash/Character/Dog.jsx
  src/components/Splash/Character/Earth.jsx
  src/components/Splash/Character/Rabbit.jsx
  src/components/Splash/Frame/Container.jsx
  src/components/Splash/Frame/Imagebox.jsx
  src/components/Splash/Frame/Title.jsx
  src/components/common/Header/ChatRoomHeader.jsx
  src/components/common/Header/HomeHeader.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Header/SearchHeader.jsx
  src/components/common/Header/UploadHeader.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Navbar/BarButtonStyle.jsx
  src/hook/useModalControl.jsx
  src/hook/useScrollTop.jsx
  src/index.js
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatInput.jsx
  src/pages/Chat/ChatPage.jsx
  src/pages/ChatList/ChatListPage.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/Follow/FollowList/FollowerList.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/NoFollowHome.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Post/CommentInput.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostEdit.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Search/Contents.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/SignUp.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/recoil/loginAtom.js
  src/recoil/userAtom.js
  src/routes/AppRouter.jsx
  src/styles/BasicLayout.jsx
  src/styles/Theme.jsx
Labels: 🔥Remove

#171 💄 posting 개행처리 css 추가
  src/components/Post/PostMain/PostMainStyle.jsx
  src/pages/Profile/ProfileModification.jsx
Labels: 🎨 Style

#172 🔨 채팅방, 프로필 신고 모달, 경고창 추가
  src/components/common/Alert/Alert.jsx
  src/components/common/Header/ChatRoomHeader.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/kakaomap/KakaoMap.jsx
  src/pages/Chat/Chat.jsx
Labels: 🔨 Refactor

#174 🐞 MoreHeader 오류 해결
  src/components/common/Header/MoreHeader.jsx
Labels: 🐞 BugFix

#175 🔨 채팅 내용 수정, splash 넘어가는 시간 수정
  public/baseprofile.svg
  src/components/common/ChatList/ChatList.jsx
  src/components/common/ChatList/chatdata.json
  src/pages/Chat/ChatPage.jsx
  src/pages/Post/CommentInput.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: 🔨 Refactor

#178 🐞 파비콘 오류 수정
  public/favicon.ico
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/index.html
  public/manifest.json
  src/pages/Post/PostCommentStyle.jsx
Labels: 🐞 BugFix

#179 🔥 manifest 파일 삭제
  public/index.html
  public/manifest.json
Labels: 🔥Remove

#180 🐞 파비콘 오류 해결
  public/index.html
Labels: 🐞 BugFix

#182 💄 코스 그리기 페이지 맵 높이 수정
  src/components/kakaomap/KakaoMap.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/AddCourse/PathDrawStyle.jsx
Labels: 🎨 Style

#185 🔨 팔로잉, 팔로우 본인 계정 버튼 미표시
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
Labels: 🔨 Refactor

#186 💄 코스 피드, 상세보기 UI 수정
  src/assets/icons/icon-location.svg
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
  src/pages/Profile/Profile.jsx
Labels: 🎨 Style
