Repository FRONTENDSCHOOL7/jubging, pull requests merged in 2023-10, with the labels that each got.

#5 README 파일 내용 생성
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
Labels: 📃 Docs

#22 📝 리드미, 컨벤션 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
Labels: 📃 Docs

#24 📝 #23 공통 컴포넌트 제작
  src/components/Alert/Alert.jsx
  src/components/Button/Button.jsx
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/components/Navbar/Navbar.jsx
Labels: 📃 Docs

#26 📝 #25 Home, NewsLetter 폴더, 파일 생성
  src/pages/Home/Home.jsx
  src/pages/NewsLetter/NewsLetter.jsx
Labels: 📃 Docs

#28 📝 #27 splash screen login start page 제작
  src/pages/Login/LoginStart.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: 📃 Docs

#32 📝 #30 글로벌스타일 및 기본레이아웃 추가
  package-lock.json
  package.json
  src/App.js
  src/styles/BasicLayout.jsx
  src/styles/GlobalStyle.jsx
  src/styles/Theme.jsx
  src/styles/font.css
Labels: 📃 Docs, 🎨 Style

#33 💄 #25 Home 레이아웃 조정 및 스타일
  src/components/Post/Post.jsx
  src/components/Post/PostFooter.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostMain.jsx
  src/pages/Home/Home.jsx
Labels: 🎨 Style

#34 💄 #23 버튼, 헤더, 네브바 컴포넌트 제작
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/components/Navbar/Navbar.jsx
  src/components/common/Alert/Alert.jsx
  src/components/common/Button/BackButton.jsx
  src/components/common/Button/BackButtonStyle.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/Button/MoreButtonStyle.jsx
  src/components/common/Header/BackSpaceHeader.jsx
  src/components/common/Header/ChatRoomHeader.jsx
  src/components/common/Header/FollowerHeader.jsx
  src/components/common/Header/FollowingHeader.jsx
  src/components/common/Header/HeaderContainer.jsx
  src/components/common/Header/HeaderContainerStyle.jsx
  src/components/common/Header/HomeHeader.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Header/SearchHeader.jsx
  src/components/common/Header/UploadHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Navbar/BarButton.jsx
  src/components/common/Navbar/BarButtonStyle.jsx
  src/components/common/Navbar/Navbar.jsx
  src/components/common/Navbar/NavbarStyle.jsx
  src/styles/BasicLayout.jsx
  src/styles/GlobalStyle.jsx
  src/styles/Theme.jsx
Labels: 🎨 Style

#38 ✨ #36 라우터 폴더 및 파일 추가
  package-lock.json
  package.json
  src/App.js
  src/components/common/Navbar/BarButton.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#40 🎨 #27 splash screen login start page 제작
  src/components/Splash/Character/Bear.jsx
  src/components/Splash/Character/Dog.jsx
  src/components/Splash/Character/Earth.jsx
  src/components/Splash/Character/Rabbit.jsx
  src/components/Splash/Frame/Container.jsx
  src/components/Splash/Frame/Imagebox.jsx
  src/components/Splash/Frame/Title.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/Login/LoginStartStyle.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/pages/SplashScreen/SplashScreenStyle.jsx
Labels: 🎨 Style

#41 ✨ #36 라우터 연결
  src/components/common/Button/BackButton.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/SignUp.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/pages/SplashScreen/SplashScreenStyle.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#44 📝 #42 검색페이지 제작
  src/App.js
  src/pages/Search/Search.jsx
Labels: 📃 Docs

#46 💄 #45 Home 및 Post 스타일링
  src/components/Post/Post.jsx
  src/components/Post/PostFooter.jsx
  src/components/Post/PostHeader.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomePosting.jsx
  src/pages/Home/NoFollowHome.jsx
  src/pages/Home/NoFollowHomeStyle.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostCommentStyle.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Post/PostFooter.jsx
  src/pages/Post/PostFooterStyle.jsx
  src/pages/Post/PostHeader.jsx
  src/pages/Post/PostHeaderStyle.jsx
  src/pages/Post/PostMain.jsx
  src/pages/Post/PostMainStyle.jsx
Labels: 🎨 Style

#47 📝 #23 UserListBox 컴포넌트 제작
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/UserList/UserListBox.jsx
  src/components/common/UserList/UserListBoxStyle.jsx
Labels: 📃 Docs

#49 📝 #48 팔로우,팔로잉 페이지 제작
  src/App.js
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
Labels: 📃 Docs

#51 💄 #45 Home 및 Post 페이지 제작
  src/pages/Home/HomePosting.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostCommentStyle.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Post/PostDividingLine.jsx
  src/pages/Post/PostDividingLineStyle.jsx
  src/pages/Post/PostHeader.jsx
  src/pages/Post/PostHeaderStyle.jsx
  src/pages/Post/Posting.jsx
Labels: 🎨 Style

#55 🎨 #45 Newsletter 페이지 제작
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/NewsLetter/NewsLetterContainer.jsx
  src/pages/NewsLetter/NewsLetterFooter.jsx
  src/pages/NewsLetter/NewsLetterFooterStyle.jsx
  src/pages/NewsLetter/NewsLetterHeader.jsx
  src/pages/NewsLetter/NewsLetterHeaderStyle.jsx
  src/pages/NewsLetter/NewsLetterMain.jsx
  src/pages/NewsLetter/NewsLetterMainStyle.jsx
  src/pages/NewsLetter/NewsLetterPosting.jsx
Labels: 🎨 Style

#59 📝 #53 Loading 페이지 제작
  src/App.js
  src/assets/images/rabbit-face.svg
  src/pages/Loading/Loading.jsx
Labels: 📃 Docs

#61 💄 #45 Home, Post, NewsLetter 페이지 및 공통 컴포넌트 수정
  src/assets/icons/icon- more-vertical.svg
  src/assets/icons/icon-chat.svg
  src/assets/icons/icon-like.svg
  src/assets/icons/icon-more-vertical.svg
  src/components/Post/PostFooter/PostFooter.jsx
  src/components/Post/PostFooter/PostFooterStyle.jsx
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/PostHeader/PostHeaderStyle.jsx
  src/components/Post/PostMain/PostMain.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/Post/Posting.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/UserList/UserListBox.jsx
  src/components/common/UserList/UserListBoxStyle.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomePosting.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/NewsLetter/NewsLetterContainer.jsx
  src/pages/NewsLetter/NewsLetterFooter.jsx
  src/pages/NewsLetter/NewsLetterFooterStyle.jsx
  src/pages/NewsLetter/NewsLetterHeader.jsx
  src/pages/NewsLetter/NewsLetterHeaderStyle.jsx
  src/pages/NewsLetter/NewsLetterMain.jsx
  src/pages/NewsLetter/NewsLetterMainStyle.jsx
  src/pages/NewsLetter/NewsLetterPosting.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Post/PostDividingLine.jsx
  src/pages/Post/PostDividingLineStyle.jsx
  src/pages/Post/PostFooter.jsx
  src/pages/Post/PostHeader.jsx
  src/pages/Post/PostHeaderStyle.jsx
  src/pages/Post/PostMain.jsx
  src/pages/Post/PostMainStyle.jsx
  src/pages/Post/Posting.jsx
  src/routes/AppRouter.jsx
Labels: 🔨 Refactor

#62 💄 #58 ChatList, ChatRoom 스타일
  src/components/common/ChatList/ChatList.jsx
  src/components/common/ChatList/ChatListStyle.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatInput.jsx
  src/pages/Chat/ChatInputStyle.jsx
  src/pages/Chat/ChatPage.jsx
  src/pages/Chat/ChatPageStyle.jsx
Labels: 🎨 Style

#63 💄 #58 AddCourse, PathDraw 페이지 스타일
  src/pages/AddCourse/AddCourse.jsx
  src/pages/AddCourse/AddCourseStyle.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/AddCourse/PathDrawStyle.jsx
Labels: 🎨 Style

#66 ✨ #60 modal컴포넌트 구현
  package-lock.json
  package.json
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/Posting.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/hook/useModalControl.jsx
  src/index.js
  src/pages/Home/Home.jsx
  src/recoil/modalStateAtom.js
Labels: ✨ Feature

#68 📃 #58 ChatListPage 제작 및 ChatPage 오타 수정
  src/pages/Chat/ChatPage.jsx
  src/pages/ChatList/ChatListPage.jsx
Labels: 📃 Docs

#69 💄 #58 Resolve styled-components prop warnings
  src/pages/Chat/ChatPage.jsx
  src/pages/Chat/ChatPageStyle.jsx
Labels: 🎨 Style

#70 🎨 Resolve styled-components prop warnings
  src/pages/Chat/ChatInput.jsx
  src/pages/Chat/ChatInputStyle.jsx
Labels: 🎨 Style

#71 ✨ 홈, 프로필, 채팅 라우터 추가 및 변경
  src/components/Post/PostFooter/PostFooter.jsx
  src/components/common/Header/HomeHeader.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#72 ✨ 채팅룸 라우터 추가
  src/components/common/ChatList/ChatList.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#73 ✨ Home, Chat 페이지 Modal 기능 구현
  src/components/Splash/Character/Bear.jsx
  src/components/Splash/Character/Dog.jsx
  src/components/Splash/Character/Earth.jsx
  src/components/Splash/Character/Rabbit.jsx
  src/components/Splash/Frame/Container.jsx
  src/components/Splash/Frame/Imagebox.jsx
  src/components/common/Header/ChatRoomHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/hook/useModalControl.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/pages/SplashScreen/SplashScreenStyle.jsx
Labels: ✨ Feature

#75 ✨ #74 회원가입, 로그인 API 추가 및 구현
  package-lock.json
  package.json
  src/api/axios.jsx
  src/api/loginAPI.jsx
  src/api/signupAPI.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/pages/Login/Login.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/SignUp.jsx
Labels: ✨ Feature

#78 ✨ 로그인 토큰 저장 기능 구현
  package-lock.json
  package.json
  src/api/axios.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/Profile.jsx
  src/recoil/loginAtom.js
Labels: ✨ Feature

#82 ✨ userAtom 추가, Profile API 이용에 따른 프로필 가져오기 구현
  src/api/profileAPI.jsx
  src/components/common/Button/MoreButton.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/recoil/userAtom.js
Labels: ✨ Feature

#83 ✨ #80 로그인 버튼 활성화 추가
  src/pages/Login/Login.jsx
Labels: ✨ Feature

#84 ✨ 라우터 변수 추가
  src/components/common/Navbar/BarButton.jsx
  src/components/common/UserList/UserListBox.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#85 ✨ 계정 정보 및 개인 프로필 정보 가져오기
  src/api/profileAPI.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/recoil/userAtom.js
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#86 🐞 #79 로그인 계정 정보 및 개인 프로필 정보 에러코드 수정
  src/pages/Home/Home.jsx
  src/pages/Profile/ProfileDetail.jsx
Labels: 🐞 BugFix

#89 ✨ 프로필 수정 기능 구현
  src/api/profileAPI.jsx
  src/components/common/Header/UploadHeader.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileModification.jsx
  src/pages/Profile/ProfileModificationStyle.jsx
Labels: ✨ Feature

#92 ✨ 홈에서 팔로우 한 게시글 불러오기
  src/api/postAPI.jsx
  src/components/Post/PostFooter/NewsPostFooter.jsx
  src/components/Post/PostFooter/PostFooter.jsx
  src/components/Post/PostFooter/PostFooterStyle.jsx
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Post/PostMain/PostMain.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/Post/Posting.jsx
  src/components/common/UserList/UserListBox.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/NoFollowHome.jsx
  src/pages/Home/NoFollowHomeStyle.jsx
Labels: ✨ Feature

#94 ✨ 유효성 검사 및 회원가입 버튼 활성화 조건 추가
  src/pages/Login/Login.jsx
  src/pages/Sign/SignUp.jsx
Labels: ✨ Feature

#95 🎨 CourseDetail 페이지 제작
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
Labels: 🎨 Style

#96 ✨ 로그인 및 회원가입 유효성검사 수정
  src/pages/Login/Login.jsx
  src/pages/Sign/SignUp.jsx
Labels: ✨ Feature

#97 ✨ 게시글 상세보기 불러오기
  src/api/postAPI.jsx
  src/components/Post/PostFooter/PostFooter.jsx
  src/components/Post/PostMain/PostMain.jsx
  src/components/Post/Posting.jsx
  src/pages/Home/Home.jsx
  src/pages/Post/Post.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#98 ✨ 팔로우 언팔로우, 팔로워 팔로잉 리스트 나열
  src/api/follow.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/pages/Follow/FollowList/FollowerList.jsx
  src/pages/Follow/FollowList/FollowerListStyle.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
Labels: ✨ Feature

#101 ✨ 게시글 및 추천 코스 가져오기
  src/api/postAPI.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#102 ✨ 추천 코스 상세 페이지 이동
  src/api/postAPI.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#105 ✨ 게시글 작성 기능
  src/api/axios.jsx
  src/api/imageAPI.jsx
  src/api/postAPI.jsx
  src/components/common/Navbar/BarButton.jsx
  src/pages/Post/Post.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/UploadStyle.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#106 ✨ 팔로워, 팔로잉 리스트 내 팔로우 언팔로우 기능
  src/pages/Follow/FollowList/FollowerList.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
Labels: ✨ Feature

#107 ✨ #104 댓글 기능 추가
  src/api/commentAPI.jsx
  src/components/common/Button/MoreButton.jsx
  src/pages/Post/CommentInput.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
Labels: ✨ Feature

#109 🐛 사진 등록 시 뜨는 에러 해결
  src/pages/Upload/Upload.jsx
Labels: ✨ Feature

#110 🎨 프로필 편집 헤더 스타일 수정
  src/api/profileAPI.jsx
  src/pages/Profile/ProfileModification.jsx
  src/pages/Profile/ProfileModificationStyle.jsx
Labels: 🎨 Style

#111 🔨 fetchPostDetail, fetchComments 함수 수정
  src/pages/Post/Post.jsx
Labels: 🔨 Refactor

#112 🔨 #104 댓글 관련 기능 수정
  src/pages/Post/CommentInput.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostComment.jsx
Labels: 🔨 Refactor

#113 ✨ 게시글 등록 시 이미지 삭제 버튼 추가
  src/api/postAPI.jsx
  src/assets/icons/icon-close.svg
  src/components/common/Header/UploadHeader.jsx
  src/pages/Post/Post.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/UploadStyle.jsx
Labels: ✨ Feature, 🎨 Style

#115 🔨 #80 회원가입시 이메일 중복에 대한 에러 핸들링 로직 추가
  src/pages/Sign/SignUp.jsx
Labels: 🔨 Refactor

#116 ♻️ #80 회원가입시 계정ID 중복에 대한 에러 핸들링 로직 추가
  src/pages/Sign/SignUp.jsx
Labels: 🔨 Refactor

#118 ✨ #117 로그인 상태에 따른 라우팅 로직 추가
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#119 ✨ 게시글 수정 및 삭제 기능 구현
  src/api/postAPI.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostEdit.jsx
  src/pages/Upload/Upload.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature

#122 🔨 #80 회원가입시 이메일, 계정ID 중복 확인 코드 수정
  src/api/signupAPI.jsx
  src/pages/Sign/SignUp.jsx
Labels: 🔨 Refactor

#123 ♻️ 로그인시 이메일 비밀번호 일치한지 확인하는 코드 변경 및 수정
  src/pages/Login/Login.jsx
Labels: 🔨 Refactor
