Repository FRONTENDSCHOOL7/jubging, pull requests merged in 2023-12, with the labels that each got.

#190 🔨 로그인 유무에 따른 URL 접근 예외처리
  src/routes/AppRouter.jsx
Labels: 🔨 Refactor

#193 🔨 상세페이지 지도 확대, 축소 및 드래그 기능 추가 / 지도 그리기 라우터 조정
  src/pages/CourseDetail/CourseDetail.jsx
  src/routes/AppRouter.jsx
Labels: 🔨 Refactor

#196 🔨 버튼 컴포넌트 수정으로 인한 버튼 비활성화 방식 수정 #191
  src/components/common/Button/Button.jsx
  src/components/kakaomap/KakaoMap.jsx
Labels: 🔨 Refactor

#197 💄 폰트 사이즈 추가 및 변경
  src/pages/Login/LoginStyle.jsx
  src/pages/Sign/ProfileStartStyle.jsx
  src/pages/Sign/SignUpStyle.jsx
  src/styles/Theme.jsx
Labels: 🎨 Style

#200 💄 버튼 컴포넌트 패딩, 높이 값 수정
  src/components/common/Button/BackButton.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Button/MoreButton.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
  src/pages/Sign/ProfileStartStyle.jsx
Labels: 🎨 Style

#198 ♻️ 좌클릭 시 버튼 비활성화 적용
  src/components/kakaomap/KakaoMap.jsx
Labels: 🔨 Refactor

#204 🔨 누적거리 및 거리 입력 시 자동입력
  src/components/kakaomap/KakaoMap.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#207 🐞 코스 등록 에러 해결
  src/pages/AddCourse/AddCourse.jsx
  src/pages/Profile/ProfileDetail.jsx
Labels: 🐞 BugFix

#209 🔨 게시물 갤러리 형식 및 아이콘 색상 전환
  src/components/Post/PostMain/PostGallery.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
Labels: 🔨 Refactor

#211 🔨 티어 컴포넌트 제작 및 갤러리 확대 효과
  src/components/Post/PostMain/PostGallery.jsx
  src/components/common/Tier/TierCard.jsx
  src/components/common/Tier/TierCardStyle.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Style

#202 🔨 헤더 컴포넌트 리팩토링 및 헤더 제목 추가
  src/components/common/Button/SearchButton.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderContainer.jsx
  src/components/common/Header/HeaderContainerStyle.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/hook/useModal.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/Chat/Chat.jsx
  src/pages/ChatList/ChatListPage.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStartStyle.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/Post/Post.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileModification.jsx
  src/pages/Search/Search.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/SignUp.jsx
  src/pages/Upload/Upload.jsx
Labels: 🔨 Refactor

#213 ✨ 코스디테일 삭제 기능 구현 #199
  src/api/postAPI.jsx
  src/components/CourseDetail/CourseDetailHeader.jsx
  src/components/CourseDetail/CourseDetailHeaderStyle.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailEdit.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
Labels: ✨ Feature, 🔨 Refactor

#214 🎨 플로깅기록 페이지 제작
  src/components/common/Navbar/BarButton.jsx
  src/pages/PloggingRecord/PloggingRecord.jsx
  src/pages/PloggingRecord/PloggingRecordStyle.jsx
  src/routes/AppRouter.jsx
Labels: 🎨 Style

#215 ✨ 공동 작업(티어카드, courseDetail more버튼 위치 조정, ploggingRecord 추가, 라우터 변경)
  src/components/CourseDetail/CourseDetailHeader.jsx
  src/components/CourseDetail/CourseDetailHeaderStyle.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Tier/TierCard.jsx
  src/components/kakaomap/KakaoMap.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailEdit.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
  src/pages/PloggingRecord/PloggingRecord.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/routes/AppRouter.jsx
Labels: ✨ Feature, 🔨 Refactor

#220 ✨ 티어 모달 제작
  src/components/common/Tier/PloggingRecordCard.jsx
  src/components/common/Tier/TierModal.jsx
  src/components/common/Tier/TierModalStyle.jsx
Labels: ✨ Feature

#221 🐞 addcourse 헤더 pathname 수정
  src/components/common/Header/Header.jsx
Labels: 🐞 BugFix
