Repository FRONTENDSCHOOL7/jubging, pull requests merged in 2024-01, with the labels that each got.

#223 🎨 반응형구현
  src/assets/images/intro-qr.png
  src/components/Post/PostHeader/PostHeaderStyle.jsx
  src/components/common/Button/AddButton.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/Input/RoundInputStyle.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/components/common/Navbar/NavbarStyle.jsx
  src/components/common/Profile/ProfileImage.jsx
  src/components/common/Profile/ProfileImageStyle.jsx
  src/components/common/UserList/UserListBoxStyle.jsx
  src/hook/useModalControl.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/Chat/ChatInput.jsx
  src/pages/Chat/ChatInputStyle.jsx
  src/pages/Post/CommentInputStyle.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/Profile/ProfileDetailStyle.jsx
  src/pages/Profile/ProfileModificationStyle.jsx
  src/pages/Search/Contents.jsx
  src/pages/Search/Search.jsx
  src/pages/Upload/UploadStyle.jsx
  src/styles/BasicLayout.jsx
  src/styles/GlobalStyle.jsx
Labels: 🎨 Style

#227 🚚 컴포넌트, 페이지 폴더 정리
  src/components/Chat/ChatInput.jsx
  src/components/Chat/ChatInputStyle.jsx
  src/components/Chat/chatdata.json
  src/components/FollowList/FollowerList.jsx
  src/components/FollowList/FollowerListStyle.jsx
  src/components/Map/KakaoMap.jsx
  src/components/Map/MapComponent.jsx
  src/components/Map/MapComponentStyle.jsx
  src/components/Post/CommentInput.jsx
  src/components/Post/CommentInputStyle.jsx
  src/components/Post/PostComment.jsx
  src/components/Post/PostCommentStyle.jsx
  src/components/Post/PostHeader/PostHeader.jsx
  src/components/Profile/ProfileDetail.jsx
  src/components/Profile/ProfileDetailStyle.jsx
  src/components/Profile/ProfileImage.jsx
  src/components/Profile/ProfileImageStyle.jsx
  src/components/Tier/PloggingRecordCard.jsx
  src/components/Tier/PloggingRecordCardStyle.jsx
  src/components/Tier/TierCard.jsx
  src/components/Tier/TierCardStyle.jsx
  src/components/Tier/TierModal.jsx
  src/components/Tier/TierModalStyle.jsx
  src/components/UserList/UserListBox.jsx
  src/components/UserList/UserListBoxStyle.jsx
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/ChatList/ChatList.jsx
  src/components/common/Header/BackSpaceHeader.jsx
  src/components/common/Header/ChatRoomHeader.jsx
  src/components/common/Header/FollowerHeader.jsx
  src/components/common/Header/FollowingHeader.jsx
  src/components/common/Header/HeaderContainer.jsx
  src/components/common/Header/HomeHeader.jsx
  src/components/common/Header/MoreHeader.jsx
  src/components/common/Header/SearchHeader.jsx
  src/components/common/Header/UploadHeader.jsx
  src/context/AuthContext.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatListStyle.jsx
  src/pages/Chat/ChatPage.jsx
  src/pages/Chat/ChatStyle.jsx
  src/pages/ChatList/ChatListPage.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Following.jsx
  src/pages/PloggingRecord/PloggingRecord.jsx
  src/pages/Post/Post.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Profile/ProfileEditStyle.jsx
  src/pages/Search/Search.jsx
  src/pages/Sign/ProfileStart.jsx
  src/routes/AppRouter.jsx
Labels: 🚚 Chrore

#232 💚 netlify.toml 수정
  netlify.toml
Labels: 🔨 Refactor

#234 🔨 웹폰트 적용
  src/assets/fonts/GMARKETSANSBOLD.OTF
  src/assets/fonts/GMARKETSANSLIGHT.OTF
  src/assets/fonts/GMARKETSANSMEDIUM.OTF
  src/components/Post/PostCommentStyle.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/common/Button/BackButton.jsx
  src/pages/AddCourse/AddCourseStyle.jsx
  src/pages/Chat/ChatListStyle.jsx
  src/pages/Chat/ChatStyle.jsx
  src/styles/GlobalStyle.jsx
  src/styles/font.css
Labels: 🔨 Refactor

#236 🥰 시맨틱마크업으로 변경
  src/components/FollowList/FollowerListStyle.jsx
  src/components/Post/PostHeader/PostHeaderStyle.jsx
  src/components/Post/PostMain/PostMainStyle.jsx
  src/components/Profile/ProfileDetail.jsx
  src/components/Profile/ProfileDetailStyle.jsx
  src/components/Profile/ProfileImageStyle.jsx
  src/components/Splash/Character/Bear.jsx
  src/components/Splash/Character/Dog.jsx
  src/components/Splash/Character/Earth.jsx
  src/components/Splash/Character/Rabbit.jsx
  src/components/Splash/Frame/Imagebox.jsx
  src/components/Tier/PloggingRecordCard.jsx
  src/components/Tier/PloggingRecordCardStyle.jsx
  src/components/Tier/TierCard.jsx
  src/components/UserList/UserListBoxStyle.jsx
  src/components/common/Button/BackButton.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/Button/SearchButton.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Navbar/BarButton.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/AddCourse/AddCourseStyle.jsx
  src/pages/AddCourse/PathDrawStyle.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatListStyle.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/PloggingRecord/PloggingRecordStyle.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Profile/ProfileEditStyle.jsx
Labels: 🥰 Accessibility

#237 🔨 label id값 추가
  src/components/Chat/ChatInput.jsx
  src/components/Post/CommentInput.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/InputStyle.jsx
  src/components/common/Input/RoundInput.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Search/Search.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/SignUp.jsx
Labels: 🥰 Accessibility

#238 🔨 컨텐츠 숨김 컨포넌트 구현 및 적용
  src/components/Post/PostMain/PostGallery.jsx
  src/components/Profile/ProfileDetail.jsx
  src/components/Profile/ProfileImage.jsx
  src/components/Tier/PloggingRecordCard.jsx
  src/components/Tier/PloggingRecordCardStyle.jsx
  src/components/Tier/TierCard.jsx
  src/components/Tier/TierModalStyle.jsx
  src/components/common/A11yHidden/A11yHidden.jsx
  src/components/common/Alert/Alert.jsx
  src/components/common/Button/AddButton.jsx
  src/components/common/Button/BackButton.jsx
  src/components/common/Button/MoreButton.jsx
  src/components/common/Button/SearchButton.jsx
  src/components/common/Modal/Modal.jsx
  src/pages/AddCourse/AddCourse.jsx
  src/pages/AddCourse/PathDraw.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/CourseDetail/CourseDetail.jsx
  src/pages/CourseDetail/CourseDetailStyle.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/LoginStart.jsx
  src/pages/Login/LoginStartStyle.jsx
  src/pages/NewsLetter/NewsLetter.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Search/Search.jsx
  src/pages/Sign/ProfileStart.jsx
  src/pages/Sign/ProfileStartStyle.jsx
  src/pages/Upload/Upload.jsx
Labels: 🥰 Accessibility
